# Generated by Django 4.2.25 on 2025-11-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentreceipt',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='receipt_number',
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='pdf_file',
            field=models.FileField(upload_to='receipts/'),
        ),
    ]
