# Generated by Django 4.2.25 on 2025-11-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='coupon',
        ),
    ]
