# Generated by Django 4.2.25 on 2025-11-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='center',
            field=models.CharField(blank=True, choices=[('Orogun', 'Orogun'), ('Samonda', 'Samonda'), ('Online', 'Online')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
    ]
