# Generated by Django 4.2.25 on 2025-12-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_customuser_center_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_used_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
