# Generated by Django 4.2.25 on 2025-10-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_customuser_amount_owed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
