# Generated by Django 4.2.25 on 2025-11-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dashboard_locked',
            field=models.BooleanField(default=False),
        ),
    ]
