# Generated by Django 4.2.25 on 2025-11-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_customuser_dashboard_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
