# Generated by Django 4.2.25 on 2025-12-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_initial'),
        ('certificates', '000X_add_obsolete_fields'),
    ]

    operations = [
    ]
