# Generated by Django 4.2.25 on 2025-12-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_merge_0003_initial_000X_add_obsolete_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issue_date']},
        ),
    ]
