# Generated by Django 4.2.25 on 2025-11-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='center',
            field=models.CharField(blank=True, choices=[('Orogun', 'Orogun'), ('Samonda', 'Samonda'), ('Online', 'Online')], max_length=20, null=True),
        ),
    ]
