# Generated by Django 4.2.25 on 2025-10-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['lesson__order'], 'verbose_name': 'Lesson Progress'},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order')},
        ),
    ]
