# Generated by Django 4.2.25 on 2025-11-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lessonprogress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='resource_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
